# YAML File with our default Logging configuration
version: 1
disable_existing_loggers: False
formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  colored_console:
    "()": 'coloredlogs.ColoredFormatter'
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class : logging.StreamHandler
    formatter: colored_console
    stream  : 'ext://sys.stderr'
root:
  level : DEBUG
  handlers:
    - console
loggers:
  coolbeans:
    level : DEBUG
  websockets:
    level: INFO
  urllib3:
    level: WARNING
